services:
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_DefaultConnection=Server=MEGANG-384.evolution.corp\\;Database=***;User Id=***daDB;password=****.
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=****.
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
  

volumes:
  mssqldata: